name: Build and test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install
        working-directory: webapp

      - name: Lint the code
        run: yarn lint
        working-directory: webapp

      - name: Docker build and push
        uses: cloudposse/github-action-docker-build-push@1.16.0
        with:
          tags: arnocol/webapp:latest  # Je Docker Hub username en de naam van de image
